Global:
  use_gpu: True
  epoch_num: 100
  log_smooth_window: 20  
  print_batch_step: 10
  save_model_dir: ./my_projects/mrz/output/name_ocr_1511/
  save_epoch_step: 5
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 200]
  # if pretrained_model is saved in static mode, load_static_weights must set to True
  cal_metric_during_train: True
  pretrained_model: 
  # pretrained_model: ./output/rec_mrz/iter_epoch_450.pdparams
  # pretrained_model: ./my_projects/mrz_ocr/pretrain_models/en_number_mobile_v2.0_rec_train/best_accuracy
  # save_inference_dir: ./my_projects/mrz_ocr/inference/rec_mrz_231031/
  save_inference_dir:
  use_visualdl: False
  infer_img:
  # for data or label process
  # character_dict_path: ./train_data/dict.txt
  character_dict_path: ./train_data/rec/mrz/character_dict.txt
  # Set the language of training, if set, select the default dictionary file
  # character_type: VN
  max_text_length: 48
  infer_mode: False
  use_space_char: false

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
  regularizer:
    name: L2
    factor: 1.0e-05
Architecture:
  model_type: rec
  algorithm: CRNN
  Transform: null
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: small
    small_stride:
    - 1
    - 2
    - 2
    - 2
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 48
  Head:
    name: CTCHead
    fc_decay: 1.0e-05
Loss:
  name: CTCLoss
PostProcess:
  name: CTCLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/rec/mrz/train_4/images
    label_file_list:
    - ./train_data/rec/mrz/train_4/gt.txt
    delimiter: ','
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecAug: null
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 32
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size_per_card: 200
    drop_last: true
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/rec/mrz/test/images
    label_file_list:
    - ./train_data/rec/mrz/test/gt.txt
    delimiter: ','
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 32
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 600
    num_workers: 4
profiler_options: null
