Global:
  debug: false
  use_gpu: true
  epoch_num: 50
  log_smooth_window: 5
  print_batch_step: 10
  save_model_dir: ./output/rec_ppocr_v47
  save_epoch_step: 1
  eval_batch_step: [0, 200]
  cal_metric_during_train: true
  pretrained_model: 
  checkpoints: output/rec_ppocr_v47/best_accuracy.pdparams
  save_inference_dir: 
  use_visualdl: false
  infer_img: 
  character_dict_path: ./train_data/dict_2.txt
  max_text_length: &max_text_length 120
  infer_mode: false
  use_space_char: true
  distributed: false
  save_res_path: ./output/rec/v4_v1


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0001
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 3.0e-05


Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform:
  Backbone:
    name: PPLCNetV3
    scale: 0.95
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 120
            depth: 2
            hidden_dims: 120
            kernel_size: [1, 3]
            use_guide: True
          Head:
            fc_decay: 0.00001
      - NRTRHead:
          nrtr_dim: 384
          max_text_length: *max_text_length

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - NRTRLoss:

PostProcess:  
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

# Train:
#   dataset:
#     name: LMDBDataSet
#     data_dir: ./train_data/rec/DB1611/
#     transforms:
#     - DecodeImage:
#         img_mode: BGR
#         channel_first: false
#     - RecConAug:
#         prob: 0.5
#         ext_data_num: 2
#         image_shape: [48, 320, 3]
#         max_text_length: *max_text_length
#     - RecAug:
#     - MultiLabelEncode:
#         gtc_encode: NRTRLabelEncode
#     - KeepKeys:
#         keep_keys:
#         - image
#         - label_ctc
#         - label_gtc
#         - length
#         - valid_ratio
#   loader:
#     shuffle: True
#     batch_size_per_card: 600
#     drop_last: True
#     num_workers: 3
Train:
  dataset:
    name: MultiScaleDataSet
    ds_width: false
    data_dir: ./train_data/rec/DB2211/
    ext_op_transform_idx: 1
    label_file_list: 
      - "./train_data/rec/DB2211/rec_gt_train.txt"
      # - "./train_data/rec/DB2211/address_lbl.txt"
      - "./train_data/rec/DB2211/en_00_lbl.txt"
      - "./train_data/rec/DB2211/en_01_lbl.txt"
      # - "./train_data/rec/DB2211/hand_vn_00_lbl.txt"
      # - "./train_data/rec/DB2211/hand_vn_02_lbl.txt"
      - "./train_data/rec/DB2211/meta_lbl.txt"
      - "./train_data/rec/DB2211/random_lbl.txt"
      - "./train_data/rec/DB2211/real_id_lbl.txt"
      - "./train_data/rec/DB2211/receipt_lbl.txt"
      - "./train_data/rec/DB2211/vi_00_lbl.txt"
      - "./train_data/rec/DB2211/vi_01_lbl.txt"
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape: [32, 512]
        max_text_length: *max_text_length
    - RecAug:
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  sampler:
    name: MultiScaleSampler
    scales: [[512, 16], [512, 24], [512, 32]]
    first_bs: &bs 104
    fix_bs: false
    divided_factor: [8, 16] # w, h
    is_training: True
  loader:
    shuffle: true
    batch_size_per_card: *bs
    drop_last: true
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/rec/DB2211/
    label_file_list:
      - "./train_data/rec/DB2211/rec_gt_test.txt"
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - RecResizeImg:
        image_shape: [3, 32, 512]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: *bs
    num_workers: 4