Global:
  use_gpu: True
  epoch_num: 100
  log_smooth_window: 20  
  print_batch_step: 10
  save_model_dir: ./my_projects/name_ocr/output/name_ocr_1511/
  save_epoch_step: 5
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 200]
  # if pretrained_model is saved in static mode, load_static_weights must set to True
  cal_metric_during_train: True
  pretrained_model: 
  # pretrained_model: ./output/rec_mrz/iter_epoch_450.pdparams
  # pretrained_model: ./my_projects/mrz_ocr/pretrain_models/en_number_mobile_v2.0_rec_train/best_accuracy
  # save_inference_dir: ./my_projects/mrz_ocr/inference/rec_mrz_231031/
  save_inference_dir:
  use_visualdl: False
  infer_img:
  # for data or label process
  character_dict_path: ./train_data/dict.txt
  # Set the language of training, if set, select the default dictionary file
  character_type: VN
  max_text_length: 48
  infer_mode: False
  use_space_char: false


Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    # learning_rate: 0.001
    learning_rate: 0.0001
  regularizer:
    name: 'L2'
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: small
    small_stride: [1, 2, 2, 2]
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 48
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: LMDBDataSet
    data_dir: ./train_data/rec/DB1511/train/
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug:

      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320] 
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 600
    drop_last: True
    num_workers: 3
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/rec/DB1511/
    label_file_list: ["./train_data/rec/DB1511/rec_gt_test.txt"]
    # delimiter: "\t"
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 600
    num_workers: 3